baseURL: https://website4rory.netlify.app/
languageCode: en-us
title: Rory Yu
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: See more
    subtitle: |-
      A PERSONAL WEBSITE BUILT FOR APPLIED STATISTICS MODULE
      AT LONDON BUSINESS SCHOOL.
    title: Hi, my name is Rory Yu
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: 50 Harrowby street
        title: Home
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ryu.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (44) 74 2131 0778
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Rory
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100006030704488
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/roryyyyyu/
      - icon: fa-github
        label: GitHub
        url: https://github.com/RoryYu327
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/roryyu/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: https://website4rory.netlify.app/
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By Rory Yu
    title: RY
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Self introduction
        title: About me
        url: blogs/rory
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: See more
    enable: yes
    subtitle: "Thank you for spending time going through this page. \r\n 
    Hope it helps you get to know me a little bit more. \r\n
    But of course you might still have questions about me and you might wish to
    directly contact me. \r\n
    So, here are my contact details and you could also so the form below to reach me."
    title: Final remarks
    url: blogs
